import { Request, Response } from "express";

import { prisma } from "../utils/prismaClient";

//* GET
export const getAllUserSuccessByUserId = async (req: Request, res: Response) => {
    const userId: string = req.params.userId;

    try {
        if (!userId) {
            throw Object.assign(new Error(), {
                status: 400,
                message: "Le param√®tre userId est absent de la requ√™te",
            });
        }

        if (isNaN(parseInt(userId, 10))) {
            throw Object.assign(new Error(), {
                status: 400,
                message: "Le param√®tre userId doit √™tre un nombre valide",
            });
        }

        const userSuccess = await prisma.userSuccess.findMany({
            where: {
                userId: parseInt(userId, 10),
            },
            include: {
                success: true,
            },
        });

        if (userSuccess.length === 0) {
            throw Object.assign(new Error(), {
                status: 404,
                message: "Succ√®s introuvables pour cet utilisateur üò¢",
            });
        }

        return res.status(200).json({ userSuccess });
    } catch (error: any) {
        return res.status(error.status || 500).json({ erreur: error.message || "Erreur interne" });
    }
};

//* PATCH
export const validateSuccess = async (req: Request, res: Response) => {
    const userSuccessId: string = req.params.id;
    const yolId: number = req.body.yolId;

    try {
        if (!userSuccessId) {
            throw Object.assign(new Error(), {
                status: 400,
                message: "Le param√®tre userSuccessId est absent du corps de la requ√™te",
            });
        }

        if (isNaN(parseInt(userSuccessId, 10))) {
            throw Object.assign(new Error(), {
                status: 400,
                message: "Le param√®tre userSuccessId doit √™tre un nombre valide",
            });
        }

        if (!yolId) {
            throw Object.assign(new Error(), {
                status: 400,
                message: "Le param√®tre yolId est absent du corps de la requ√™te",
            });
        }

        if (isNaN(yolId)) {
            throw Object.assign(new Error(), {
                status: 400,
                message: "Le param√®tre yolId doit √™tre un nombre valide",
            });
        }

        const userSuccess = await prisma.userSuccess.findUnique({
            where: { id: parseInt(userSuccessId, 10) },
        });

        if (!userSuccess) {
            throw Object.assign(new Error(), {
                status: 404,
                message: "Succ√®s utilisateur introuvable üò¢",
            });
        }

        if (userSuccess.isCompleted) {
            throw Object.assign(new Error(), {
                status: 400,
                message: "Le succ√®s utilisateur a d√©j√† √©t√© compl√©t√©",
            });
        }

        const matchingSuccess = await prisma.success.findUnique({
            where: { id: userSuccess.successId },
        });

        if (!matchingSuccess) {
            throw Object.assign(new Error(), {
                status: 404,
                message: "Succ√®s associ√© au succ√®s utilisateur introuvable",
            });
        }

        if (userSuccess && matchingSuccess) {
            if (userSuccess.actualAmount !== matchingSuccess.amountNeeded) {
                throw Object.assign(new Error(), {
                    status: 400,
                    message: "Le montant requis pour valider le succ√®s n'a pas √©t√© atteint",
                    "montant actuel": userSuccess.actualAmount,
                    "montant requis": matchingSuccess.amountNeeded,
                });
            }
        }

        await prisma.userSuccess.update({
            where: { id: parseInt(userSuccessId, 10) },
            data: { isCompleted: true },
        });

        const updatedYol = await prisma.yol.update({
            where: { id: yolId },
            data: { xp: { increment: matchingSuccess.successXp } },
        });

        if (!updatedYol) {
            throw Object.assign(new Error(), {
                status: 404,
                message: "Erreur lors de l'ajout d'experience au Yol",
            });
        }

        return res.status(200).json({ message: "Votre Yol a gagn√© de l'exp√©rience !", yol: updatedYol });
    } catch (error: any) {
        return res.status(error.status || 500).json({ erreur: error.message || "Erreur interne" });
    }
};

export default {
    getAllUserSuccessByUserId,
    validateSuccess,
};
